name: Deploy Production 🚀

on:
  release:
    types: [published, edited]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # ... (Delay, checkout, and SSH setup steps remain the same)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare deployment
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER_NAME_PRODUCTION }}@${{ secrets.SSH_HOST_PRODUCTION }} << 'EOF'
            set -e
            APP_PROD_PATH="/home/ubuntu/production"

            # Ensure known hosts is correctly configured
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            # Pull the latest image (adjust image name and tag)
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pacmusic:${{ github.event.release.tag_name }}

            # Restart or update services in the docker-compose file
            sudo docker compose up --build -d nginx pacmusic-prod-1 pacmusic-prod-2
          EOF

      - name: Test Hit Endpoint (Using production domain)
        run: |
          sleep 30  # Wait for services to be ready
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER_NAME_PRODUCTION }}@${{ secrets.SSH_HOST_PRODUCTION }} "curl https://bhismaroi.site"
