name: Deploy Production 🚀

on:
  release:
    types: [published, edited]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}

      - name: Prepare deployment
        run: |
          # Debugging: Print SSH key for verification
          echo "SSH private key:"
          echo "${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}" | head -n 1  # Ensure only first line is printed for security

          # Ensure known hosts are correctly configured
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Debugging: Test SSH connection
          ssh -T git@github.com || true  # Use "git" as SSH user if applicable

          # Ensure directory permissions are correct
          sudo chown -R $USER:$USER /home/ubuntu/production || true
          sudo chmod -R 755 /home/ubuntu/production || true

          # Prepare deployment
          APP_PROD_PATH="/home/ubuntu/production"
          if [ -d "$APP_PROD_PATH" ]; then
            cd $APP_PROD_PATH
            docker compose down pacmusic-prod  # Assuming the Docker Compose file is named 'docker-compose.yml'
            git pull origin main
          else
            git clone ${{ secrets.GIT_URL }} $APP_PROD_PATH
            cd $APP_PROD_PATH
          fi

      - name: Generate .env file
        run: |
          echo "APP_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/pacmusic" > .env
          echo "APP_TAG=${{ github.event.release.tag_name }}" >> .env
          echo "APP_PROD_PORT=${{ secrets.APP_PROD_PORT }}" >> .env
          echo "MINIO_PROD_ENDPOINT=${{ secrets.MINIO_PROD_ENDPOINT }}" >> .env
          echo "MINIO_PROD_ACCESS_KEY=${{ secrets.MINIO_PROD_ACCESS_KEY }}" >> .env
          echo "MINIO_PROD_SECRET_KEY=${{ secrets.MINIO_PROD_SECRET_KEY }}" >> .env

      - name: Start Docker Compose for production
        run: docker compose up --build --detach pacmusic-prod

      - name: Test Hit Endpoint
        run: |
          sleep 30  # Wait for services to be ready
          curl http://localhost:${{ secrets.APP_PROD_PORT }}
